# Generated by Django 2.2.5 on 2019-09-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients.photos'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
