# Generated by Django 2.2.5 on 2019-09-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190909_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='age',
            field=models.IntegerField(),
        ),
    ]
